-- 코드를 입력하세요
SELECT CAR_ID,
    CASE WHEN MAX(AVAILABILITY_1) = 1 # 하나라도 대여중이면 대여중으로 표기
    THEN '대여중'
    ELSE '대여 가능' END AS "AVAILABILITY"
-- 각 차의 대여 여부 조회
FROM(SELECT CAR_ID,
        CASE WHEN START_DATE <= DATE '2022-10-16' AND END_DATE >= DATE '2022-10-16'
        THEN 1 ELSE 0
        END AS "AVAILABILITY_1" FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A
GROUP BY CAR_ID
ORDER BY CAR_ID DESC